name: Create Pull Request to Another Repository

on:
  push:
    branches:
      - main
    paths:
      - "test/test.js"

jobs:
  syncAndCreatePR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'RamyEB'
          git config --global user.email 'ramyelb@gmail.com'

      - name: Sync files to the other repository and create Pull Request
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          BRANCH_NAME=sync-discover-doc-$(date +%s)
          SOURCE_REPO="github.com/RamyEB/RamyEB"
          FILE_PATH_SOURCE_REPO="test/test.js"
          TARGET_REPO="github.com/RamyEB/RamyEBTest"
          FILE_PATH_TARGET_REPO="test/test.js"
          PR_API_URL="https://api.github.com/repos/RamyEB/RamyEBTest/pulls"
          COMMIT_MESSAGE="doc: add new changes from wallet-api doc"

          git clone --depth 1 https://${TARGET_REPO_TOKEN}@${SOURCE_REPO}
          git clone --depth 1 https://${TARGET_REPO_TOKEN}@${TARGET_REPO}

          # Copy file and check if there are changes
          cp -u RamyEB/${FILE_PATH_SOURCE_REPO} RamyEBTest/${FILE_PATH_TARGET_REPO}

          # Create new branch and push changes
          cd RamyEBTest
          git checkout -b $BRANCH_NAME
          git add $FILE_PATH_TARGET_REPO
          git commit -m "${COMMIT_MESSAGE}"
          git push origin $BRANCH_NAME

          # Create Pull Request
          RESPONSE=$(curl -X POST -H "Authorization: token ${TARGET_REPO_TOKEN}" \
              -d '{"title":"Merging documentation from wallet-api","head":"'"$BRANCH_NAME"'","base":"main"}' \
              ${PR_API_URL})
          echo "GitHub API Response: $RESPONSE"
